### ISSUE TITLE
AMWG output files not viewable on the web

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#21]
In my most recent test (`/p/cscratch/acme/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/input/run.cfg`), AMWG appears to have run successfully, but the output files are not accessible from the web.

The link provided by **acme_processflow** is:
https://acme-viewer.llnl.gov/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG
but the full address should be
https://acme-viewer.llnl.gov/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/amwg/0001-0010

However, the files are not viewable. I first thought it was a permission issue, so I fixed them using

```
cd /var/www/acme/acme-diags/golaz1
find 20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison -type d -print0 | xargs -0 chmod 755
find 20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison -type f -print0 | xargs -0 chmod 644
```

But that did not fix the issue. I think the real problem is that the files under `/var/www/acme/acme-diags/golaz1` are symbolic links to files on `/p/cscratch/acme`. I would not be surprised if the web server (for security reason) did not follow symbolic links.

Another problem is that I have two sub-directories for the same years:

```
cd /var/www/acme/acme-diags/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/amwg
ls -1
0001-0010
0001-0010_b3acccc3
```

Are the figures I'm looking for under `0001-0010` or `0001-0010_b3acccc3`?

**Comment by sterlingbaldwin** [comment]
When you run a job with the same experiment name as one that already exists, instead of over writing the plots I just added a random string to the end. I think it would be better if instead of random characters it was the date you ran it, this would remove the confusion of which one was run when. Alternately I could just let the user overwrite their output, but I thought it would be better to error on the side of safety.

**Comment by golaz** [comment]
Still not working. The files are not viewable on the web. Did you try yourself?

**Comment by sterlingbaldwin** [comment]
This was working for me on Friday, but its something thats been giving me trouble for a while. I had a run last week that didnt get its output hosted, but I thought I had fixed the issue. What version are you running?

**Comment by golaz** [comment]
processflow               0.3.17                    devel    acme/label/nightly

**Comment by sterlingbaldwin** [comment]
Looking through your run log I'm seeing something wonky is going on with the amwg hosting. I'll focus on this issue today.

**Comment by sterlingbaldwin** [comment]
You were right when you said the symlinks might lead to permissions issues, which is one of the problems here. All the amwg plots you ran should be available now, but I havent fixed the underlying issue yet.

https://acme-viewer.llnl.gov/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/amwg/0001-0010/index.html

**Comment by sterlingbaldwin** [comment]
Fixed in the new nightly.

**Comment by golaz** [comment]
Reopening because unfortunately this is still not working with the latest version: 0.3.20-devel 

![screen](https://user-images.githubusercontent.com/15743046/30995257-cc72ad86-a46d-11e7-9087-53cda0069880.png)

**Comment by golaz** [comment]
Here is what I do to manually fix the permissions after the fact:

```
cd /p/cscratch/acme/golaz1
find 20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison -type d -print0 | xargs -0 chmod 755
find 20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison -type f -print0 | xargs -0 chmod 644
cd /var/www/acme/acme-diags/golaz1
find 20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison -type d -print0 | xargs -0 chmod 755
```
